// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RimrockMVC.Data;

namespace RimrockMVC.Migrations
{
    [DbContext(typeof(RimrockDBContext))]
    [Migration("20190416215841_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RimrockMVC.Models.FavLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cost");

                    b.Property<string>("Name");

                    b.Property<int>("RegionId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.ToTable("FavLocations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = "$",
                            Name = "TestLocation",
                            RegionId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Cost = "$",
                            Name = "TestLocation2",
                            RegionId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Cost = "$",
                            Name = "TestLocation3",
                            RegionId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            Cost = "$",
                            Name = "TestLocation4",
                            RegionId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            Cost = "$",
                            Name = "TestLocation5",
                            RegionId = 1,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("RimrockMVC.Models.FavRetailer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("RegionId");

                    b.Property<string>("Specialty");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.ToTable("FavRetailers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "TestRetailer",
                            RegionId = 1,
                            Specialty = "Stuff",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "TestRetailer2",
                            RegionId = 1,
                            Specialty = "Stuff",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "TestRetailer3",
                            RegionId = 1,
                            Specialty = "Stuff",
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "TestRetailer4",
                            RegionId = 1,
                            Specialty = "Stuff",
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "TestRetailer5",
                            RegionId = 1,
                            Specialty = "Stuff",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("RimrockMVC.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "TestUserOne"
                        },
                        new
                        {
                            ID = 2,
                            Name = "TestUserTwo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
